name: Run Tests Sequentially

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.1.0

      # ---- Admin ----
      - name: Install dependencies for admin
        working-directory: ./admin
        run: npm install

      - name: Run tests for admin
        working-directory: ./admin
        run: npm run test

      # ---- Main ----
      - name: Install dependencies for main
        working-directory: ./main
        run: npm install

      - name: Run tests for name
        working-directory: ./main
        run: npm run test
